In [1]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution() #open session

In [13]:
#Functions with math operators
a = tf.constant([3., 3., 2.])
b = tf.constant([2., 2., 2.])

In [19]:
#sum, diff, prod, quot
sum = tf.add(a, b)
diff = tf.subtract(a, b)
prod = tf.multiply(a, b)
quot = tf.divide(a, b)
dot = tf.tensordot(a, b, 1)

with tf.compat.v1.Session() as sess:
    print(sess.run(sum))
    print(sess.run(diff))
    print(sess.run(prod))
    print(sess.run(quot))
    print(sess.run(dot))

[5. 5. 4.]
[1. 1. 0.]
[6. 6. 4.]
[1.5 1.5 1. ]
16.0
