In [38]:
#import libraries
import tensorflow as tf
tf.compat.v1.disable_eager_execution() #open session

In [4]:
#tensor constant
t1 = tf.constant([1,2,3,4,5])
with tf.compat.v1.Session() as sess:
    print(sess.run(t1))

[1 2 3 4 5]


In [6]:
#tensor constant multidimensional
t2 = tf.constant([[1,2,3], [4,5,6]])
with tf.compat.v1.Session() as sess:
    print(sess.run(t2))

[[1 2 3]
 [4 5 6]]


In [8]:
#tensors with 0
zero_tensor = tf.zeros([3])
with tf.compat.v1.Session() as sess:
    print(sess.run(zero_tensor))

[0. 0. 0.]


In [10]:
#tensor with 1 (matrix 4x4)
one_tensor = tf.ones([4,4])
with tf.compat.v1.Session() as sess:
    print(sess.run(one_tensor))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
#fill tensor
#structure tf.fill([shape], value)
fill_tensor = tf.fill([2,3], 34.0)
fill_tensor

<tf.Tensor 'Fill_12:0' shape=(2, 3) dtype=float32>

In [27]:
with tf.compat.v1.Session() as sess:
    print(sess.run(fill_tensor))

[[34. 34. 34.]
 [34. 34. 34.]]


In [29]:
#Sequencies
lin_tensor = tf.linspace(start=5., stop=9., num=5)
with tf.compat.v1.Session() as sess:
    print(sess.run(lin_tensor))

[5. 6. 7. 8. 9.]


In [41]:
#range
range_tensor = tf.range(start = 3., limit=7., delta = 0.5)
with tf.compat.v1.Session() as sess:
    print(sess.run(range_tensor))

[3.  3.5 4.  4.5 5.  5.5 6.  6.5]


In [49]:
#random variables
rnd_tensor = tf.random.normal([10], dtype = tf.float64)
with tf.compat.v1.Session() as sess:
    print(sess.run(rnd_tensor))

[ 2.15947533 -0.85258956 -0.61436244 -0.81744459 -0.41950755 -1.02776284
 -0.48258672 -1.1135425  -1.6963816  -0.74405798]
